# Generated by Django 3.0.5 on 2020-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='archive'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
