# Generated by Django 3.0.6 on 2020-05-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(db_index=True, max_length=500, verbose_name='ФИО')),
                ('dates', models.CharField(db_index=True, max_length=350, verbose_name='Даты')),
                ('bio', models.TextField(blank=True, db_index=True, verbose_name='Биография')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
