# Generated by Django 3.0.6 on 2020-06-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='famille',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tree.Famille', verbose_name='Род'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='details',
            field=models.TextField(blank=True, db_index=True, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Фото'),
        ),
    ]
